### ISSUE TITLE
Teensy 4 MAC

### ISSUE THREAD

**Issue by FrankBoesing** [sstaub/TeensyID#3]
Can be obtained with 
`static void teensyMAC(uint8_t *mac)
{
  uint32_t m1 = HW_OCOTP_MAC1;
  uint32_t m2 = HW_OCOTP_MAC0;
  mac[0] = m1 >> 8;
  mac[1] = m1 >> 0;
  mac[2] = m2 >> 24;
  mac[3] = m2 >> 16;
  mac[4] = m2 >> 8;
  mac[5] = m2 >> 0;
}`

**Comment by sstaub** [comment]
Is there a #define for Teensy 4 processor, like `__MK66FX1M0__` ?

**Comment by FrankBoesing** [comment]
Yes, it follows a new scheme:
ARDUINO_TEENSY40

**Comment by sstaub** [comment]
I make an update for Teensy 4 MAC address and new board scheme. In the moment there is no support for UID for Teensy 4.
