### ISSUE TITLE
TeensyID on platformio registry not up to date

### ISSUE THREAD

**Issue by arnoson** [sstaub/TeensyID#5]
I tried installing TeensyID via platformio (https://platformio.org/lib/show/1587/TeensyID) and it installed an older version that doesn't support teensy 4. Could you update the library on platformio?

**Comment by sstaub** [comment]
The last version is 1.3.0 which is also registered on pio.

**Comment by arnoson** [comment]
I just realized I wrote Teensy 4 but actually ment Teensy 4.1.
I compared the version 1.3 that I installed with platformio with this github repository and it seems the Teensy 4.1 support is not included in 1.3? Maybe I'm missing something but I can only get it running with a Teensy 4.1 if I install the library manually from github.

**Comment by sstaub** [comment]
Maybe this is a bug with the registry of PIO because the Github lib is ok. In the moment you must install manually.
Can you look inside the library PIO is using and tell me which version is described in the library.json ?

**Comment by arnoson** [comment]
library.json describes `"version": "1.3.0"`. I compared the `TeensyID.cpp` file that PIO downloads with the one in the repository and indeed they are different files.

![Screenshot from 2020-09-29 14-34-33](https://user-images.githubusercontent.com/15122993/94559128-0e4de000-0261-11eb-8ae5-1371997cca14.png)

**Comment by sstaub** [comment]
I made a new release with some minor improvements and I hope in the next days there will the right library on PIO.

**Comment by arnoson** [comment]
Just downloaded `1.3.1` with PIO and everything works, thank you!
