### ISSUE TITLE
Causes Teensy 3.2 to restart sometimes

### ISSUE THREAD

**Issue by Mike4U** [sstaub/TeensyID#6]
I added teensyMAC() to a bunch of code as a response to a terminal command.  Sometimes when it is called the Teensy restarts.  I use interrupts  but none are happening when this occurs.

Should I only call this from setup()and store the value?

**Comment by sstaub** [comment]
Yes, you should call it only in setup() storing the values in variables. My be that there are race conditions with interrupts,
